<a href="https://colab.research.google.com/github/Ganesh-4691/Test/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)
x_ones =  torch.ones_like(x_data)
print(x_ones)
x_random = torch.rand_like(x_data, dtype = torch.float)
print(x_random)
print (f"stored:\n{x_data.device}\n")


tensor([[1, 2],
        [3, 4]])
tensor([[1, 1],
        [1, 1]])
tensor([[0.4618, 0.0583],
        [0.5177, 0.3564]])
stored:
cpu



In [ ]:
shape = (4,4)
one_tensor = torch.ones(shape)
rand_tensor = torch.rand(shape)
if torch.cuda.is_available():
  one_tensor = one_tensor.to("cuda")
  rand_tensor = rand_tensor.to("cuda")
  print(f"first_column:{one_tensor[:, 0]}")
  print(f"last_column:{rand_tensor[1,:]}")
  print(f"random_tenosr:\n{rand_tensor}")


first_column:tensor([1., 1., 1., 1.], device='cuda:0')
last_column:tensor([0.0108, 0.3744, 0.2060, 0.4768], device='cuda:0')
random_tenosr:
tensor([[0.8047, 0.4458, 0.8981, 0.3148],
        [0.0108, 0.3744, 0.2060, 0.4768],
        [0.6677, 0.4978, 0.8912, 0.7996],
        [0.3779, 0.2252, 0.2898, 0.5413]], device='cuda:0')


In [ ]:
t1 = torch.cat([one_tensor,rand_tensor], dim=1)
print(t1)

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 0.8047, 0.4458, 0.8981, 0.3148],
        [1.0000, 1.0000, 1.0000, 1.0000, 0.0108, 0.3744, 0.2060, 0.4768],
        [1.0000, 1.0000, 1.0000, 1.0000, 0.6677, 0.4978, 0.8912, 0.7996],
        [1.0000, 1.0000, 1.0000, 1.0000, 0.3779, 0.2252, 0.2898, 0.5413]],
       device='cuda:0')


In [ ]:
t = torch.ones(5)
n = t.numpy()
print(f"numpy\n: {n}")

numpy
: [1. 1. 1. 1. 1.]


# New section